version: "3"
services:
    db:
      container_name: myMongo
      image: mongo:4.4.1-bionic
      ports:
       - "27017:27017"
    api:
      container_name: node-api
      build: .
      ports :
       - "3000:3000"
